spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: api-biblioteca
          uri: http://localhost:8082
          predicates:
            - Path=/biblioteca/**
        - id: api-usuario
          uri: http://localhost:8081
          predicates:
            - Path=/usuarios/**
        - id: api-emprestimo
          uri: http://localhost:8080
          predicates:
            - Path=/emprestimo/**

server:
  port: 8083

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG